import { redirect } from '@sveltejs/kit';

import dotenv from 'dotenv';

dotenv.config();

export async function load() {
	const dataRes = await fetch(
		`https://raw.githubusercontent.com/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}/${process.env.BRANCH}/data/data.json`
	);
	const data = await dataRes.json();
	throw redirect(302, `http://127.0.0.1:5173/changelog/${encodeURI(data.table[0]?.name)}`);
}
export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 10
	}
};
