import { error } from '@sveltejs/kit';

export async function load() {
	try {
        const changelogRes = await fetch(`https://raw.githubusercontent.com/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}/${process.env.BRANCH}/data/changelog.json`)
		const changelog = await changelogRes.json()
        return { changelog };
	} catch (e) {
		console.log(e);
		throw new error(500);
	}
}

export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 10
	}
};
